### 获取根路径
* 方便测试

In [1]:
import sys
import os

# 获取当前工作目录
# Trytorch\test
current_dir = os.getcwd()

# 获取父目录
# Trytorch
project_dir = os.path.dirname(current_dir)

# 现在的路径即为项目根路径,可以找到主包trytorch
sys.path.append(project_dir)

import trytorch as torch
import numpy as np
import torch as pytorch
from trytorch import ops

c:\Users\GameDesign\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\_environment.py:215: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(
c:\Users\GameDesign\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [5]:
###################################################################### 
# 广播测试
######################################################################
a = torch.Tensor([[1,2,3]], device=None,dtype=int)
b = a.broadcast_to((4,3))
b.backward()
b.grad, a.grad, 

(tensor([[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]], dtpye=int32),
 tensor([[4 4 4]], dtpye=int32))

In [7]:
###################################################################### 
# 矩阵乘法测试
######################################################################

_ = torch.Tensor(pytorch.arange(0,6.0))
A = _.reshape((2,3))
B = A.transpose((-1,-2))
C = A @ B

loss = C.sum()
loss.backward()
A.grad, B.grad

(tensor([[ 6. 10. 14.]
  [ 6. 10. 14.]], dtpye=float64),
 tensor([[3. 3.]
  [5. 5.]
  [7. 7.]], dtpye=float64))

In [8]:
## pytorch
_ = pytorch.tensor(pytorch.arange(0,6.0),requires_grad=True)
# A = _.reshape(2,3)
# B = A.T
A = pytorch.tensor(np.arange(0,6.0).reshape(2,3),requires_grad=True)
B = pytorch.tensor(np.arange(0,6.0).reshape(2,3).T,requires_grad=True)
C = A @ B

A.retain_grad()
B.retain_grad()

# PyTorch 的 backward() 函数默认只能对标量输出计算梯度
loss = C.sum()
loss.backward()
A.grad, B.grad

C:\Users\GameDesign\AppData\Local\Temp\ipykernel_20232\3948603456.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  _ = pytorch.tensor(pytorch.arange(0,6.0),requires_grad=True)


(tensor([[3., 5., 7.],
         [3., 5., 7.]], dtype=torch.float64),
 tensor([[3., 3.],
         [5., 5.],
         [7., 7.]], dtype=torch.float64))

In [2]:
###################################################################### 
# 自动求导测试
######################################################################

# 前向计算
val = 1

v1 = torch.Tensor(val, device=None,dtype=int)
v2 = ops.exp(v1)
v3 = v2 + 1
v4 = v2 * v3
y = v4

# 反向传播
y.backward()
print()
print("----------------------grads--------------------")
print("v4.grad:", v4.grad)  # dy/dv4 = 1
print("v3.grad:", v3.grad)  # dy/dv3
print("v2.grad:", v2.grad)  # dy/dv2
print("v1.grad:", v1.grad)  # dy/dv1


----------------------grads--------------------
v4.grad: tensor(1.0, dtpye=float64)
v3.grad: tensor(2.718281828459045, dtpye=float64)
v2.grad: tensor(6.43656365691809, dtpye=float64)
v1.grad: tensor(17.496394026320345, dtpye=float64)


In [ ]:
val = 1

# 前向
v1 = pytorch.tensor(val, device=None,dtype=float,requires_grad=True)
v2 = pytorch.exp(v1)
v3 = v2 + 1
v4 = v2 * v3
y = v4
print("y:", y)

# 反向
# 保留中间变量的梯度
v2.retain_grad()
v3.retain_grad()
v4.retain_grad()
y.backward()

print("---------------grads---------------")
print("v4.grad:", v4.grad)  # dy/dv4 = 1
print("v3.grad:", v3.grad)  # dy/dv3
print("v2.grad:", v2.grad)  # dy/dv2
print("v1.grad:", v1.grad)  # dy/dv1