### 获取根路径
* 方便测试

In [2]:
import sys
import os
# 获取当前工作目录
# Trytorch\test
current_dir = os.getcwd()
# 获取父目录
# Trytorch
project_dir = os.path.dirname(current_dir)
# 现在的路径即为项目根路径,可以找到主包trytorch
sys.path.append(project_dir)


import numpy as np


import trytorch as torch
from trytorch import ops
from trytorch import init
from trytorch import nn

c:\Users\GameDesign\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\_environment.py:215: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(


In [3]:
np.random.seed(42)
x_array = np.random.rand(1,1,12,12)  
x = torch.Tensor(x_array)
y = nn.MaxPooling2D(kernel_size=4, stride=4)(x)
y.backward()
print(x.grad)

tensor([[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.]]]], dtpye=float32)


In [4]:
import torch as pytorch
from torch import nn as pnn
np.random.seed(42)
x_array = np.random.rand(1,1,12,12)  
x = pytorch.tensor(x_array,requires_grad=True)
x.retain_grad()

y = pnn.MaxPool2d(kernel_size=4,stride=4)(x)

grad_output = pytorch.ones_like(y)
y.backward(gradient=grad_output)
print(x.grad)

tensor([[[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.]]]],
       dtype=torch.float64)


In [8]:
a = np.random.rand(1,4,4,1)    
b = torch.Tensor(a)
b = b.transpose((1,3))
b.shape

(1, 1, 4, 4)

In [7]:
# N,H,W,C
np.random.seed(42)
a = np.random.rand(1,6,6,1)     
print(a.transpose(0,3,1,2))            
a = torch.Tensor(a)
b = ops.maxPooling2D(a,3,3)
print(b.cached_data.transpose(0,3,1,2))
b.backward()
a.grad.cached_data.transpose(0,3,1,2)

[[[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
   [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]
   [0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643]
   [0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
   [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
   [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]]]
[[[[0.95071431 0.96990985]
   [0.78517596 0.96563203]]]]


array([[[[0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0.]]]], dtype=float32)

In [6]:
init.randb(2,3,3,p = 0.05,dtype="float32")

tensor([[[0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], dtpye=float32)

In [2]:

np.random.seed(42)
x = torch.Tensor(np.random.randn(4, 3))  # batch=4, dim=3

bn1 = nn.BatchNorm1d(3)

out1 = bn1.forward(x)

out1

tensor([[-1.04313887 -0.25883405  1.69428946]
 [ 0.94434811 -0.46367483 -0.22585502]
 [ 1.05314787  1.67594423 -0.73829412]
 [-0.95435711 -0.95343535 -0.73014031]], dtpye=float64)

In [3]:
class TryNet(nn.Module):
    def __init__(self,fin,fhid,fclass):
        super().__init__()
        self.Flatten = nn.Flatten()
        self.Linear1 = nn.Linear(fin,fhid)
        self.f1 = nn.ReLU()
        self.Linear2 = nn.Linear(fhid,fclass)

    def forward(self, x):
        x = self.Flatten(x)
        x = self.Linear1(x)
        x = self.f1(x)
        x = self.Linear1(x)

nt = TryNet(3,5,2)
print(nt)

{'training': True, 'Flatten': <trytorch.nn.nn.Flatten object at 0x000002584059B580>, 'Linear1': <trytorch.nn.nn.Linear object at 0x000002584059BF70>, 'f1': <trytorch.nn.nn.ReLU object at 0x000002584059B880>, 'Linear2': <trytorch.nn.nn.Linear object at 0x000002584059BE80>}


In [2]:
# init.rand(3,4,low=100,high=1000)
a = torch.Tensor([2,3,4])
init.kaiming_uniform(3,4),init.xavier_uniform(3,4)

(tensor([[ 0.99486625  1.1838446   0.71551657  0.46399543]
  [ 0.75924844 -0.9497253   0.5305862  -1.3494016 ]
  [ 0.64362353 -1.3410091  -0.704432   -0.84754986]], dtpye=float32),
 tensor([[ 0.30923706  0.36427802 -0.799866    0.3997933 ]
  [ 0.11338341 -0.4254143   0.23471844  0.8686739 ]
  [-0.19285916 -0.28480503 -0.25579557  0.1547388 ]], dtpye=float32))

In [15]:
class A:
    def __init__(self):
        self.a = True     
        pass

    def print(self):
        print(self.__dict__)

class B(A):
    def __init__(self,**kwargs):
        super().__init__()
        for key, value in kwargs.items():
            setattr(self, key, value)




a = A()
a.print()
b = B(c = 6, d = 7)
b.print()

print(isinstance(b,B))
print(isinstance(b,A))
print(isinstance(a,B))

{'a': True}
{'a': True, 'c': 6, 'd': 7}
True
True
False
