In [1]:
import sys
import os

# 获取当前工作目录
# Trytorch\test
current_dir = os.getcwd()

# 获取父目录
# Trytorch
project_dir = os.path.dirname(current_dir)

# 现在的路径即为项目根路径,可以找到主包trytorch
sys.path.append(project_dir)

In [4]:
import trytorch as torch
from trytorch import ops
from trytorch.array_api import array_api 

a = torch.Tensor(array_api.arange(1,5).reshape(1,2,2),requires_grad=False)
dilate_a = ops.dilate(a,(1,2),1)
print(dilate_a)
undilate_b = ops.undilate(dilate_a,(1, 2), 1)

undilate_b



tensor([[[1. 0. 2. 0.]
  [0. 0. 0. 0.]
  [3. 0. 4. 0.]
  [0. 0. 0. 0.]]], dtpye=float32)
compact array : <class 'numpy.ndarray'>


tensor([[[1. 2.]
  [3. 4.]]], dtpye=float32)

compact array : <class 'numpy.ndarray'>
tensor([[1 2]
 [3 4]], dtpye=int32)
