### 获取根路径
* 方便测试

In [1]:
import sys
import os
# 获取当前工作目录
# Trytorch\test
current_dir = os.getcwd()
# 获取父目录
# Trytorch
project_dir = os.path.dirname(current_dir)
# 现在的路径即为项目根路径,可以找到主包trytorch
sys.path.append(project_dir)


import numpy as np


import trytorch as torch
from trytorch import ops
from trytorch import init
from trytorch import nn

c:\Users\GameDesign\AppData\Local\Programs\Python\Python39\lib\site-packages\cupy\_environment.py:215: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(
c:\Users\GameDesign\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
class TryNet(nn.Module):
    def __init__(self,fin,fhid,fclass):
        super().__init__()
        self.Flatten = nn.Flatten()
        self.Linear1 = nn.Linear(fin,fhid)
        self.f1 = nn.ReLU()
        self.Linear2 = nn.Linear(fhid,fclass)

    def forward(self, x):
        x = self.Flatten(x)
        x = self.Linear1(x)
        x = self.f1(x)
        x = self.Linear1(x)

nt = TryNet(3,5,2)
print(nt)

{'training': True, 'Flatten': <trytorch.nn.nn.Flatten object at 0x000002584059B580>, 'Linear1': <trytorch.nn.nn.Linear object at 0x000002584059BF70>, 'f1': <trytorch.nn.nn.ReLU object at 0x000002584059B880>, 'Linear2': <trytorch.nn.nn.Linear object at 0x000002584059BE80>}


In [2]:
# init.rand(3,4,low=100,high=1000)
a = torch.Tensor([2,3,4])
init.kaiming_uniform(3,4),init.xavier_uniform(3,4)

(tensor([[ 0.99486625  1.1838446   0.71551657  0.46399543]
  [ 0.75924844 -0.9497253   0.5305862  -1.3494016 ]
  [ 0.64362353 -1.3410091  -0.704432   -0.84754986]], dtpye=float32),
 tensor([[ 0.30923706  0.36427802 -0.799866    0.3997933 ]
  [ 0.11338341 -0.4254143   0.23471844  0.8686739 ]
  [-0.19285916 -0.28480503 -0.25579557  0.1547388 ]], dtpye=float32))

In [15]:
class A:
    def __init__(self):
        self.a = True     
        pass

    def print(self):
        print(self.__dict__)

class B(A):
    def __init__(self,**kwargs):
        super().__init__()
        for key, value in kwargs.items():
            setattr(self, key, value)




a = A()
a.print()
b = B(c = 6, d = 7)
b.print()

print(isinstance(b,B))
print(isinstance(b,A))
print(isinstance(a,B))

{'a': True}
{'a': True, 'c': 6, 'd': 7}
True
True
False
